In [1]:
import cv2

In [2]:
import tensorflow as tf

In [3]:
import keras

In [4]:
const_1 = tf.constant(0)


In [5]:
const_1.shape

TensorShape([])

In [6]:
const_1.numpy()


0

In [7]:
const_2 = tf.constant([10,20,30,40,50,60,70,80])


In [8]:
const_2.shape


TensorShape([8])

In [9]:
const_2.numpy()


array([10, 20, 30, 40, 50, 60, 70, 80])

In [10]:
const_3 = tf.constant([[10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70],
                      [10,20,30,40,50,60,70]])

In [11]:
const_3.shape


TensorShape([3, 7])

In [12]:
const_3.numpy()


array([[10, 20, 30, 40, 50, 60, 70],
       [10, 20, 30, 40, 50, 60, 70],
       [10, 20, 30, 40, 50, 60, 70]])

In [13]:
const_4 =  tf.constant([[[10,20,30,40,50,60,70],
                       [10,20,30,40,50,60,70],
                       [10,20,30,40,50,60,70],

                       [10,20,30,40,50,60,70],
                       [10,20,30,40,50,60,70],
                       [10,20,30,40,50,60,70]]])

In [14]:
const_4.shape    #3 dimension(A tensor)


TensorShape([1, 6, 7])

In [15]:
const_4.numpy()


array([[[10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70],
        [10, 20, 30, 40, 50, 60, 70]]])

In [16]:
#This is N-Dimentional representation of an Numpy Array Representing Various Ranks Like:
#scalar : rank =0, vector : rank=1, matrix: rank=2, tensor:3 or more


In [17]:
X= tf.constant([[8],
                [9],
                [10],
                [11],
                [21],
                [23]])
X.shape

TensorShape([6, 1])

In [18]:
W = tf.Variable([[10],
                 [11],
                 [12],
                 [13],
                 [14],
                 [15]])
W.shape

TensorShape([6, 1])

In [19]:
WT = tf.transpose(W)
WT.numpy()

array([[10, 11, 12, 13, 14, 15]])

In [20]:
# Y = WT*X+bias
tf.tensordot(WT , X, axes = 1)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1081]])>

In [21]:
tf.tensordot(X, WT, axes = 1)

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[ 80,  88,  96, 104, 112, 120],
       [ 90,  99, 108, 117, 126, 135],
       [100, 110, 120, 130, 140, 150],
       [110, 121, 132, 143, 154, 165],
       [210, 231, 252, 273, 294, 315],
       [230, 253, 276, 299, 322, 345]])>

In [22]:
tf.tensordot(X, WT, axes = 0)

<tf.Tensor: shape=(6, 1, 1, 6), dtype=int32, numpy=
array([[[[ 80,  88,  96, 104, 112, 120]]],


       [[[ 90,  99, 108, 117, 126, 135]]],


       [[[100, 110, 120, 130, 140, 150]]],


       [[[110, 121, 132, 143, 154, 165]]],


       [[[210, 231, 252, 273, 294, 315]]],


       [[[230, 253, 276, 299, 322, 345]]]])>

#Keras is high level API based on Tensorflow, to create deep level learning neural network easily. Dense Neural Network(DNN),CNN And RNN